name: security

on:
    pull_request:
        branches: [main]

jobs:
    security:
        name: Security
        runs-on: ubuntu-latest

        steps:
            - name: Check out code
              uses: actions/checkout@v4
      
            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                go-version: "1.23.0"

            - name: Install gosec
              run: go install github.com/securego/gosec/v2/cmd/gosec@latest
      
            - name: Run gosec
              run:  gosec ./...
